### ISSUE TITLE
Meta-issue: Changes before next release

### ISSUE THREAD

**Issue by okamsn** [okamsn/loopy#155]
We want these changes before the next release:

- [x] Do more efficient initialization of iteration variables (#142, #144).
- [x] Deprecate `:result-type` (#154). Use `finally-return` instead.
- [x] Deprecate `:init` (#146). Use `with` instead.
- [x] Unify tests (#128, #144)
- [x] Make `always`, `never`, and `thereis` consistent with other commands (#145).

Things we probably want:

- [ ] Split `seq` and `sequence`. `seq` should use `seq.el`. `sequence` should be only for the basic sequence type (lists, arrays, vectors, strings, etc.) (#150)
- [ ] Deprecate `beginning` as an alternative for `start` with `:at`. Simplifies checks and tests.

Things we might want:

~~- [ ] Deprecate `reduce` and `accumulate` in favor of `set-accum` (#153)? We should have some kind of `reduce`, but I dislike how, to be consistent with other commands, its argument order differs from `cl-reduce` and `seq-reduce`.~~

**Comment by okamsn** [comment]
Released version 0.13.0.
