### ISSUE TITLE
Add to ELPA once settled

### ISSUE THREAD

**Issue by okamsn** [okamsn/loopy#74]
Loopy is now on MELPA.

Once things are more settled, it makes sense to try to add it to ELPA as well.

TODO
- [ ] #48
- [x] Hopefully #70
- [x] #69
- [x] Make decisions for #62
- [x] #65 (being worked on in #73)
- [x] Double check #43. ~~This seems fixed on Emacs 28, but also requires testing with other Emacs versions.~~
- [x] Maybe #45
- [ ] Maybe #60
- [ ] If simple, #44
- [ ] #103 
- [x] #104

**Comment by okamsn** [comment]
Added #103 and #104 to the to-do list. Those should be the last of the major feature changes before seeking feedback. The rest of the Iterate features are a bit niche.

**Comment by okamsn** [comment]
Loopy is now on Non-GNU ELPA as well as Melpa.
